# Generated by Django 3.1.4 on 2020-12-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NMUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(error_messages={'unique': 'Username Already Used'}, max_length=40, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Email Already Used'}, max_length=254, unique=True)),
                ('password', models.CharField(max_length=40)),
                ('firstName', models.CharField(max_length=40)),
                ('lastName', models.CharField(max_length=40)),
            ],
        ),
    ]
